server:
  servlet:
    context-path: /api
jwt:
  secret: mysteam

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/steam
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      format_sql: true
      ddl-auto: create
    show-sql: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE